create table stimule.settings
(
    id                     bigint unsigned auto_increment
        primary key,
    title                  varchar(255)               null,
    description            varchar(255)               null,
    keywords               varchar(255)               null,
    kassa_id               varchar(255)               null,
    kassa_secret1          varchar(255)               null,
    kassa_secret2          varchar(255)               null,
    kassa_key              varchar(50)                null,
    wallet_id              varchar(500)               null,
    wallet_secret          varchar(500)               null,
    wallet_desc            varchar(50)                null,
    vlito_id               varchar(50)                null,
    vlito_secret           varchar(50)                null,
    min_payment_sum        double(8, 2)               null,
    min_bonus_sum          double(8, 2)               null,
    min_withdraw_sum       double(8, 2)               null,
    min_dep_withdraw       int                        null,
    withdraw_request_limit int                        null,
    vk_url                 varchar(255)               null,
    tg_channel             varchar(250)               null,
    tg_bot                 varchar(250)               null,
    vk_id                  varchar(50)                null,
    vk_token               varchar(255)               null,
    vk_service_token       varchar(500)               null,
    bot_timer              double(8, 2)               null,
    file_version           int           default 1    not null,
    antiminus              int           default 0    not null,
    daily_bonus_min        double(16, 2) default 0.00 not null,
    daily_bonus_max        double(16, 2) default 0.00 not null,
    hourly_bonus_min       double(16, 2) default 0.00 not null,
    hourly_bonus_max       double(16, 2) default 0.00 not null,
    onetime_bonus          float         default 0    not null,
    telegram_chat_id       bigint                     null,
    telegram_token         varchar(300)               null,
    referral_domain        varchar(50)                null,
    referral_reward        double(16, 2) default 0.00 not null,
    deposit_per_n          int           default 0    not null,
    deposit_sum_n          double(16, 2) default 0.00 not null,
    created_at             timestamp                  null,
    updated_at             timestamp                  null
)
    collate = utf8mb4_unicode_ci;

