create table stimule.users
(
    id               bigint unsigned auto_increment
        primary key,
    unique_id        varchar(16)                 not null,
    username         varchar(256)                not null,
    email            varchar(255)                null,
    balance          double(255, 2) default 0.00 not null,
    password         varchar(255)                null,
    auto_payment     tinyint        default 0    not null,
    reset_token      varchar(255)                null,
    freespins        int                         null,
    fs_slot          int                         null,
    fs_amount        int                         null,
    freeround_id     text                        null,
    cashback         double                      null,
    promo_limit      timestamp                   null,
    promo_limit2     timestamp                   null,
    fs_promo_limit   timestamp                   null,
    fs_promo_limit2  timestamp                   null,
    bonus_bank       double                      null,
    repost           int            default 0    not null,
    bonus_balance    float(16, 2)   default 0.00 not null,
    wager            double(16, 2)  default 0.00 not null,
    slots_wager      double(16, 2)               not null,
    wager_status     int            default 1    not null,
    avatar           varchar(300)                null,
    vk_id            bigint                      null,
    tg_id            varchar(50)    default '0'  not null,
    vk_username      varchar(255)                null,
    dice             double(16, 2)  default 0.00 not null,
    mines            double(16, 2)  default 0.00 not null,
    bubbles          double(16, 2)  default 0.00 not null,
    wheel            double(16, 2)  default 0.00 not null,
    slots            double(16, 2)  default 0.00 null,
    plinko           double                      not null,
    total_reposts    int            default 0    not null,
    is_bot           tinyint(1)     default 0    not null,
    is_admin         int            default 0    not null,
    is_youtuber      int            default 0    not null,
    is_worker        int            default 0    not null,
    admin_role       text                        null,
    referral_use     int            default 0    null,
    referral_send    int            default 0    not null,
    referral_balance double(16, 2)  default 0.00 not null,
    ref_1_lvl        double(16, 2)  default 0.00 not null,
    ref_2_lvl        double(16, 2)  default 0.00 not null,
    ref_3_lvl        double(16, 2)  default 0.00 not null,
    ban              int            default 0    not null,
    limit_payment    int            default 0    not null,
    auth_token       varchar(255)                null,
    game_token       varchar(255)                null,
    game_token_date  varchar(255)                null,
    current_currency varchar(255)                null,
    bonus_use        int            default 0    not null,
    bonus_daily      bigint         default 0    not null,
    bonus_hourly     bigint         default 0    not null,
    vk_bonus_use     int            default 0    not null,
    tg_bonus_use     int            default 0    not null,
    created_ip       varchar(255)                null,
    used_ip          varchar(255)                null,
    videocard        varchar(255)                null,
    fingerprint      varchar(255)                null,
    logs_length      varchar(255)                null,
    current_id       int                         null,
    current_bet      double(16, 2)               null,
    remember_token   varchar(100)   default ''   not null,
    auto_withdraw    int                         null,
    created_at       timestamp                   null,
    updated_at       timestamp                   null
)
    collate = utf8mb4_unicode_ci;

create index updated_at
    on stimule.users (updated_at);

